import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'bn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, any>> = {
  bn: {
    nav: {
      home: 'হোম',
      about: 'আমাদের সম্পর্কে',
      aboutInstitute: 'এ এম আই টি সম্পর্কে',
      goals: 'লক্ষ্য ও উদ্দেশ্য',
      features: 'বৈশিষ্ট্যসমূহ',
      policies: 'নীতিমালা',
      directors: 'পরিচালক প্যানেল',
      founderDirector: 'প্রতিষ্ঠাতা পরিচালক',
      curriculum: 'পাঠ্যক্রম কমিটি',
      teachers: 'শিক্ষক প্যানেল',
      courses: 'কোর্সসমূহ',
      quranNazira: 'তাজবীদসহ কুরআন শিক্ষা',
      quranHifz: 'কুরআন হিফজ',
      quranTranslation: 'অনুবাদসহ কুরআন শিক্ষা',
      hadithHifz: 'বুখারী ও মুসলিম হিফজ',
      kidsIslam: 'শিশুদের ইসলাম শিক্ষা',
      arabicLanguage: 'আরবী ভাষা',
      admission: 'ভর্তি সংক্রান্ত',
      admissionProcess: 'ভর্তি প্রক্রিয়া ও যোগ্যতা',
      admissionForm: 'ফরম ও ভর্তি ফি',
      courseFees: 'কোর্স ফি',
      notice: 'নোটিশ বোর্ড',
      contact: 'যোগাযোগ',
      donation: 'ডোনেশন',
    },
    home: {
      title: `আল-মা'আরিফ ইন্টারন্যাশনাল ইনস্টিটিউট`,
      subtitle: `বিশ্বের প্রতিটি ঘরে কুরআন ও হাদীসের আলো পৌঁছে দেওয়া।`,
      enrollNow: 'এখনই ভর্তি হন',
      learnMore: 'আরও জানুন',
      ourBeginning: 'আমাদের সূচনা',
      beginningText: 'বর্তমান সময়ে আমরা দ্বীনের এক গভীর সংকটময় অধ্যায় পার করছি। চারদিকে ফিতনার ঝড়—নাস্তিকতা, বস্তুবাদ, অবিশ্বাস ও বিভ্রান্তির স্রোত পৃথিবীজুড়ে ছড়িয়ে পড়েছে। তবুও, এই হতাশার ঘন অন্ধকারের ভেতরেও আশার এক ফালি আলোর ঝলকানি দেখা যায়—একদল স্বপ্নবাজ, দ্বীনের প্রতি অনুরাগী তরুণ-তরুণীর উদ্যোগে প্রতিষ্ঠিত হয় "আল-মাআরিফ ইন্টারন্যাশনাল ইনস্টিটিউট"।',
      established: 'প্রতিষ্ঠার তারিখ',
      establishedDate: '১২ অক্টোবর ২০২৫ ঈসায়ী / ২০ রবিউস্ সানি ১৪৪৭ হিজরি / ২৭ আশ্বিন ১৪৩২ বঙ্গাব্দ',
      features: 'আমাদের বিশেষ বৈশিষ্ট্যসমূহ',
      oneToOne: 'ওয়ান টু ওয়ান ক্লাস',
      oneToOneDesc: 'একজন শিক্ষক, একজন ছাত্র — সম্পূর্ণ মনোযোগ এবং দ্রুত অগ্রগতি।',
      flexibleSchedule: 'সুবিধামতো সময়',
      flexibleScheduleDesc: 'আপনার সুবিধামতো সময়ে পড়াশোনা করুন।',
      qualifiedTeachers: 'অভিজ্ঞ শিক্ষক',
      qualifiedTeachersDesc: 'পুরুষদের জন্য শিক্ষক এবং মহিলাদের জন্য শিক্ষিকা।',
      freeTrial: 'ফ্রি ট্রায়াল ক্লাস',
      freeTrialDesc: 'ভর্তির আগে একাধিক ট্রায়াল ক্লাসের সুযোগ।',
      ourCourses: 'আমাদের কোর্সসমূহ',
      coursesSubtitle: 'সম্পূর্ণ পাঠ্যক্রম এবং অভিজ্ঞ শিক্ষক দ্বারা সম্পূর্ণ ইসলামী শিক্ষা।',
      viewCourse: 'কোর্স দেখুন',
      startJourney: 'আজই আপনার ইসলামিক শিক্ষার যাত্রা শুরু করুন',
      startJourneyDesc: 'একটি ফ্রি ট্রায়াল ক্লাসের জন্য আবেদন করুন এবং মানসম্পন্ন ইসলামী শিক্ষার স্বাদ নিন।',
      fillForm: 'ভর্তি ফরম পূরণ করুন',
      contactUs: 'যোগাযোগ করুন',
    },
    about: {
      title: 'আমাদের সম্পর্কে',
      subtitle: `আল-মা'আরিফ ইন্টারন্যাশনাল ইনস্টিটিউট — দ্বীনের আলো ছড়িয়ে দেওয়ার অঙ্গীকার`,
      ourBeginning: 'প্রতিষ্ঠানের সূচনা',
      beginningText1: 'বর্তমান সময়ে আমরা দ্বীনের এক গভীর সংকটময় অধ্যায় পার করছি। চারদিকে ফিতনার ঝড়—নাস্তিকতা, বস্তুবাদ, অবিশ্বাস ও বিভ্রান্তির স্রোত পৃথিবীজুড়ে ছড়িয়ে পড়েছে। মানুষ কুরআনের হেদায়াত থেকে দূরে সরে যাচ্ছে, রাসুলুল্লাহ ﷺ এর পবিত্র হাদীস অনুসরণ তো দূরের কথা—অনেকেই আজ তা অস্বীকার করার দুঃসাহস দেখাচ্ছে।',
      beginningText2: 'তবুও, এই হতাশার ঘন অন্ধকারের ভেতরেও আশার এক ফালি আলোর ঝলকানি দেখা যায়—একদল স্বপ্নবাজ, দ্বীনের প্রতি অনুরাগী তরুণ-তরুণীর উদ্যোগে।',
      foundingTitle: `আল-মা'আরিফ ইন্টারন্যাশনাল ইনস্টিটিউটের সূচনা`,
      foundingText: `এই সংকটাপূর্ণ সময়ে, দ্বীনের আলো মানুষের অন্তরে জ্বালানোর দৃঢ় অঙ্গীকার নিয়ে, একঝাঁক তরুণ ওলামায়ে কেরাম এবং দ্বীনদার জেনারেল শিক্ষিত ব্যক্তিবর্গের উদ্যোগে প্রতিষ্ঠিত হয় অনলাইনভিত্তিক ইসলামিক শিক্ষা প্রতিষ্ঠান "আল-মা'আরিফ ইন্টারন্যাশনাল ইনস্টিটিউট"।`,
      established: 'প্রতিষ্ঠার তারিখ',
      establishedDate: '১২ অক্টোবর ২০২৫ ঈসায়ী / ২০ রবিউস্ সানি ১৪৪৭ হিজরি / ২৭ আশ্বিন ১৪৩২ বঙ্গাব্দ',
      ourVision: 'আমাদের ভিশন',
      visionText: 'বিশ্বের প্রতিটি ঘরে কুরআন ও হাদীসের আলো পৌঁছে দেওয়া। দিকভ্রান্ত মানুষকে দ্বীনের সরল ও সুন্দর পথে ফিরিয়ে আনা। জ্ঞান, আমল ও আখলাকের সমন্বয়ে মানবতার কল্যাণে একটি আদর্শ প্রজন্ম গড়ে তোলা।',
      ourMission: 'আমাদের মিশন',
      missionText: 'কুরআন ও সুন্নাহর আলোকে খাঁটি ইসলামী শিক্ষা প্রদান করা। আধুনিক প্রযুক্তির মাধ্যমে দ্বীনি শিক্ষাকে সহজলভ্য করা। যোগ্য ও নৈতিকভাবে দৃঢ় মুসলিম প্রজন্ম গড়ে তোলা।',
      ourValues: 'আমাদের মূল্যবোধ',
      value1: 'ইখলাস (আন্তরিকতা)',
      value1Desc: 'শুধুমাত্র আল্লাহর সন্তুষ্টির জন্য কাজ করা।',
      value2: 'মানসম্মত শিক্ষা',
      value2Desc: 'উচ্চমানের পাঠ্যক্রম ও যোগ্য শিক্ষক প্রদান।',
      value3: 'সহজলভ্যতা',
      value3Desc: 'সবার জন্য শিক্ষার সুযোগ সহজ করা।',
      value4: 'ধারাবাহিকতা',
      value4Desc: 'নিয়মিত মনিটরিং ও মূল্যায়ন।',
      value5: 'বিশ্বস্ততা',
      value5Desc: 'সততা ও সততার সাথে দায়িত্ব পালন।',
      value6: 'উদ্ভাবন',
      value6Desc: 'আধুনিক ও কার্যকর পদ্ধতিতে শিক্ষা প্রদান।',
    },
    goals: {
      title: 'লক্ষ্য ও উদ্দেশ্য',
      subtitle: 'আমাদের স্বপ্ন ও অঙ্গীকার',
      mainGoalTitle: 'আমাদের মূল লক্ষ্য',
      mainGoalText: 'বিশ্বের প্রতিটি ঘরে কুরআন ও হাদীসের আলো পৌঁছে দেওয়া এবং একটি প্রজন্ম গড়ে তোলা, যারা জ্ঞান, আমল ও আখলাকের সমন্বয়ে মানবতার কল্যাণে কাজ করবে এবং পৃথিবীকে আলোকিত করবে আল্লাহর দীন দিয়ে।',
      goal1: 'বৈশ্বিক প্রচার',
      goal1Desc: 'বিশ্বের প্রতিটি ঘরে কুরআন ও হাদীসের আলো পৌঁছে দেওয়া',
      goal2: 'সঠিক পথ প্রদর্শন',
      goal2Desc: 'দিকভ্রান্ত মানুষকে দ্বীনের সরল ও সুন্দর পথে ফিরিয়ে আনা',
      goal3: 'প্রজন্ম গঠন',
      goal3Desc: 'জ্ঞান, আমল ও আখলাকের সমন্বয়ে আদর্শ প্রজন্ম তৈরি করা',
      goal4: 'ইলম বিস্তার',
      goal4Desc: 'কুরআন ও সুন্নাহর সঠিক জ্ঞান প্রচার ও প্রসার করা',
      goal5: 'মানসম্মত শিক্ষা',
      goal5Desc: 'আন্তর্জাতিক মানের অনলাইন ইসলামিক শিক্ষা নিশ্চিত করা',
      goal6: 'সহজ প্রবেশাধিকার',
      goal6Desc: 'প্রযুক্তির মাধ্যমে সবার জন্য ইসলামী শিক্ষা সহজলভ্য করা',
      commitmentsTitle: 'আমাদের অঙ্গীকার',
      commitment1: 'প্রতিটি শিক্ষার্থীকে ব্যক্তিগত মনোযোগ প্রদান করা।',
      commitment2: 'সর্বোচ্চ মানের শিক্ষা উপকরণ ও পদ্ধতি ব্যবহার করা।',
      commitment3: 'শিক্ষার্থীদের নৈতিক ও চারিত্রিক উৎকর্ষতা বিকাশে সহায়তা করা।',
      commitment4: 'কুরআন ও সুন্নাহর সঠিক ও স্পষ্ট বোঝাপড়া প্রদান করা।',
      commitment5: 'সহজ, আরামদায়ক ও কার্যকর শিক্ষার পরিবেশ বজায় রাখা।',
    },
    features: {
      title: 'আমাদের বৈশিষ্ট্যসমূহ',
      subtitle: 'যে বিশেষত্বগুলো আমাদের আলাদা করে',
      feature1: 'ওয়ান বাই ওয়ান ক্লাস',
      feature1Desc: 'একজন শিক্ষক, একজন ছাত্র—সম্পূর্ণ ব্যক্তিগত মনোযোগ',
      feature2: 'গ্রুপ ক্লাস',
      feature2Desc: '৩-৫ জনের ছোট গ্রুপে কার্যকর শিক্ষা',
      feature3: 'নমনীয় সময়সূচি',
      feature3Desc: 'আপনার সুবিধামতো সময়ে ক্লাস করার সুযোগ',
      feature4: 'অভিজ্ঞ শিক্ষক-শিক্ষিকা',
      feature4Desc: 'পুরুষদের জন্য শিক্ষক ও মহিলাদের জন্য শিক্ষিকা',
      feature5: 'ফ্রি ট্রায়াল ক্লাস',
      feature5Desc: 'ভর্তির আগে একাধিক ফ্রি ক্লাসের সুযোগ',
      feature6: 'দ্রুত শিক্ষা',
      feature6Desc: 'মাত্র ৪ মাসে সুন্দরভাবে কুরআন পড়তে শিখুন',
      feature7: 'সার্বক্ষণিক মনিটরিং',
      feature7Desc: 'শিক্ষার্থীদের অগ্রগতি নিয়মিত পর্যবেক্ষণ',
      feature8: 'মাসিক পরীক্ষা',
      feature8Desc: 'নিয়মিত মূল্যায়ন ও প্রতিবেদন প্রদান',
      feature9: 'সময় ব্যবস্থাপনা',
      feature9Desc: 'প্রতিটি কোর্সের ক্লাস সপ্তাহে ৫ দিন; আলোচনা সাপেক্ষে দিন বাড়ানো/কমানো সম্ভব',
      classMethodTitle: 'ক্লাস পরিচালনা পদ্ধতি',
      classMethodText: 'আমাদের প্রতিটি ক্লাস সম্পূর্ণ অনলাইনে পরিচালিত হয়, যাতে শিক্ষার্থীরা ঘরে বসেই সহজে শিখতে পারে।',
      platformsTitle: 'ব্যবহৃত প্ল্যাটফর্ম',
    },
    policies: {
      title: 'নীতিমালা',
      subtitle: 'আমাদের প্রতিষ্ঠানের নিয়ম ও নীতি',
      classPolicyTitle: 'ক্লাস সংক্রান্ত নীতিমালা',
      classPolicy1: 'প্রতিটি ক্লাসে সময়মতো উপস্থিত থাকতে হবে। ক্লাস শুরুর ৫ মিনিট আগে প্রস্তুত থাকুন।',
      classPolicy2: 'ক্লাসে অংশগ্রহণের জন্য স্থিতিশীল ইন্টারনেট সংযোগ নিশ্চিত করুন।',
      classPolicy3: 'ক্লাসে মনোযোগী থাকতে হবে এবং শিক্ষকের নির্দেশনা অনুসরণ করতে হবে।',
      classPolicy4: `প্রতিটি "ওয়ান টু ওয়ান" ক্লাস ৪০-৪৫ মিনিট, আর "গ্রুপ ক্লাস" ৫০-৬০ মিনিট হয়ে থাকে। আলোচনা সাপেক্ষে সময় কমানো/বাড়ানো সম্ভব।`,
      attendanceTitle: 'উপস্থিতি ও ছুটি',
      attendance1: 'ক্লাস মিস করলে অন্তত ২৪ ঘণ্টা আগে শিক্ষককে জানাতে হবে।',
      attendance2: 'জরুরি পরিস্থিতিতে মেকআপ ক্লাসের ব্যবস্থা করা হবে।',
      attendance3: 'পূর্ব বিজ্ঞপ্তি ছাড়া পর পর ৩টি ক্লাস অনুপস্থিত থাকলে সতর্কতা দেওয়া হবে।',
      conductTitle: 'আচরণবিধি',
      conduct1: 'শিক্ষক ও সহপাঠীদের সাথে সর্বদা সম্মান প্রদর্শন করতে হবে।',
      conduct2: 'ক্লাসের সময় ইসলামিক আদব ও শিষ্টাচার বজায় রাখতে হবে।',
      conduct3: 'যেকোনো ধরনের অনৈতিক বা অনুপযুক্ত আচরণ সহ্য করা হবে না।',
      conduct4: 'শিক্ষক অথবা সহপাঠিদের সঙ্গে পূর্ব পরিচিতি ছাড়া আর্থিক লেনদেনে জড়ানো উচিত নয়।',
      paymentTitle: 'পেমেন্ট ও রিফান্ড নীতি',
      payment1: 'প্রতি মাসের ১ থেকে ৫ তারিখের মধ্যে মাসিক ফি পরিশোধ করতে হবে।',
      payment2: 'ভর্তি ফি কোনো অবস্থাতেই ফেরতযোগ্য নয়।',
      payment3: 'কোর্স শুরুর পর বাতিলের ক্ষেত্রে কোনো রিফান্ড দেওয়া হবে না।',
      payment4: 'প্রথম ৭ দিনের মধ্যে কোর্স বাতিল করলে ৫০% রিফান্ড প্রদান করা হবে।',
    },
    footer: {
      about: `আল-মা'আরিফ`,
      institute: `ইন্টারন্যাশনাল ইনস্টিটিউট`,
      description: `বিশ্বের প্রতিটি ঘরে কুরআন ও হাদীসের আলো পৌঁছে দেওয়া আমাদের লক্ষ্য।`,
      quickLinks: 'দ্রুত লিংক',
      aboutUs: 'আমাদের সম্পর্কে',
      courses: 'কোর্সসমূহ',
      admissionProcess: 'ভর্তি প্রক্রিয়া',
      teachers: 'শিক্ষক প্যানেল',
      contact: 'যোগাযোগ',
      socialMedia: 'সোশ্যাল মিডিয়া',
      rights: `আল-মা'আরিফ ইন্টারন্যাশনাল ইনস্টিটিউট। সর্বস্বত্ব সংরক্ষিত।`,
      establishedDate: `প্রতিষ্ঠার তারিখ: ১২ অক্টোবর ২০২৫ ঈসায়ী / ২০ রবিউস্ সানি ১৪৪৭ হিজরি / ২৭ আশ্বিন ১৪৩২ বঙ্গাব্দ`,
    },
    contact: {
      title: 'কোন পরামর্শ?',
      subtitle: 'আমরা আপনার সেবায় সর্বদা প্রস্তুত। যেকোনো প্রশ্ন বা পরামর্শের জন্য যোগাযোগ করুন।',
      formTitle: 'যোগাযোগ ফরম',
      name: 'নাম',
      namePlaceholder: 'আপনার সম্পূর্ণ নাম লিখুন',
      email: 'ইমেইল',
      emailPlaceholder: 'example@email.com',
      phone: 'মোবাইল নম্বর',
      phonePlaceholder: '+880 __________',
      subject: 'বিষয়',
      subjectPlaceholder: 'বিষয় লিখুন',
      message: 'বার্তা',
      messagePlaceholder: 'এখানে আপনার বার্তা লিখুন',
      sendMessage: 'বার্তা পাঠান',
      contactInfo: 'যোগাযোগের তথ্য',
      officeHours: 'অফিস সময়',
      officeHoursText: 'শনিবার – বৃহস্পতিবার: সকাল ৯টা – রাত ৮টা',
      friday: 'শুক্রবার: বন্ধ',
      emergencySupport: 'জরুরী সহায়তা',
      emergencyText: 'জরুরি বিষয়ে সরাসরি আমাদের হটলাইনে যোগাযোগ করুন:',
      hotline: 'হটলাইন',
      successTitle: 'সফল!',
      successMessage: 'আপনার বার্তা সফলভাবে প্রেরিত হয়েছে।',
      errorTitle: 'ত্রুটি!',
      errorMessage: 'বার্তা প্রেরণে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
      validationError: 'সব বাধ্যতামূলক ঘর পূরণ করুন।',
    },
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About Us',
      aboutInstitute: 'About AMIT',
      goals: 'Goals & Objectives',
      features: 'Features',
      policies: 'Policies',
      directors: 'Directors Panel',
      founderDirector: 'Founder Director',
      curriculum: 'Curriculum Committee',
      teachers: 'Teachers Panel',
      courses: 'Courses',
      quranNazira: 'Quran with Tajweed',
      quranHifz: 'Quran Memorization',
      quranTranslation: 'Quran with Translation',
      hadithHifz: 'Bukhari & Muslim Hifz',
      kidsIslam: 'Islamic Education for Kids',
      arabicLanguage: 'Arabic Language',
      admission: 'Admission',
      admissionProcess: 'Admission Process & Eligibility',
      admissionForm: 'Form & Admission Fee',
      courseFees: 'Course Fees',
      notice: 'Notice Board',
      contact: 'Contact',
      donation: 'Donation',
    },
    home: {
      title: 'Al-Maarif International Institute',
      subtitle: 'Spreading the light of the Quran and Hadith to every home around the world.',
      enrollNow: 'Enroll Now',
      learnMore: 'Learn More',
      ourBeginning: 'Our Beginning',
      beginningText: 'Today, the Ummah is passing through a critical chapter — a time of spiritual crisis. The storms of atheism, materialism, disbelief, and confusion are sweeping across the globe. Yet, amidst this darkness, a ray of hope emerges — a group of visionary, faith-driven young men and women came together to establish Al-Maarif International Institute.',
      established: 'Date of Establishment',
      establishedDate: '12 October 2025 CE / 20 Rabi al-Thani 1447 AH / 27 Ashwin 1432 BS',
      features: 'Our Distinctive Features',
      oneToOne: 'One-on-One Classes',
      oneToOneDesc: 'One teacher, one student — full attention for faster progress.',
      flexibleSchedule: 'Flexible Schedule',
      flexibleScheduleDesc: 'Study at the time most convenient for you.',
      qualifiedTeachers: 'Qualified Instructors',
      qualifiedTeachersDesc: 'Male teachers for brothers and female teachers for sisters.',
      freeTrial: 'Free Trial Classes',
      freeTrialDesc: 'Experience multiple trial sessions before enrollment.',
      ourCourses: 'Our Courses',
      coursesSubtitle: 'Comprehensive curriculum and experienced instructors offering complete Islamic education.',
      viewCourse: 'View Course',
      startJourney: 'Start Your Islamic Learning Journey Today',
      startJourneyDesc: 'Apply for a Free Trial Class and experience the taste of quality Islamic education.',
      fillForm: 'Fill Out the Admission Form',
      contactUs: 'Contact Us',
    },
    about: {
      title: 'About Us',
      subtitle: 'Al-Maarif International Institute — Committed to Spreading the Light of Islam',
      ourBeginning: 'Our Beginning',
      beginningText1: `In today's world, we are passing through a critical era for the religion of Islam. The storm of fitnah—atheism, materialism, disbelief, and confusion—has spread across the globe. People are drifting away from the guidance of the Qur'an; and following the noble Hadith of the Prophet Muhammad ﷺ has become rare—many even dare to deny them altogether.`,
      beginningText2: 'Yet, amidst this darkness of despair, a ray of hope shines—through the efforts of a group of passionate, faith-driven young men and women.',
      foundingTitle: 'The Founding of Al-Maarif International Institute',
      foundingText: `At this crucial time, with a firm commitment to rekindle the light of Islam in people's hearts, a group of young scholars and religiously devoted, educated individuals established Al-Ma'arif International Institute, an online-based Islamic educational platform.`,
      established: 'Established on',
      establishedDate: '12 October 2025 (Gregorian) / 20 Rabi al-Thani 1447 (Hijri) / 27 Ashwin 1432 (Bengali Calendar)',
      ourVision: 'Our Vision',
      visionText: `To bring the light of the Qur'an and Hadith to every home. To guide misguided souls back to the straight and beautiful path of Islam. To nurture a generation that embodies knowledge, righteous deeds, and noble character for the welfare of humanity.`,
      ourMission: 'Our Mission',
      missionText: `To provide authentic Islamic education based on the Qur'an and Sunnah. To make religious education easily accessible through modern technology. To develop a generation of competent and morally upright Muslims.`,
      ourValues: 'Our Core Values',
      value1: 'Ikhlas (Sincerity)',
      value1Desc: 'Working solely for the pleasure of Allah.',
      value2: 'Quality Education',
      value2Desc: 'Offering a high-standard curriculum with qualified teachers.',
      value3: 'Accessibility',
      value3Desc: 'Ensuring learning opportunities are easy for everyone.',
      value4: 'Consistency',
      value4Desc: 'Maintaining regular monitoring and evaluation.',
      value5: 'Trustworthiness',
      value5Desc: 'Fulfilling our responsibilities with honesty and integrity.',
      value6: 'Innovation',
      value6Desc: 'Delivering education through modern and effective methods.',
    },
    goals: {
      title: 'Goals & Objectives',
      subtitle: 'Our Vision and Commitment',
      mainGoalTitle: 'Our Core Mission',
      mainGoalText: `To spread the light of the Qur'an and Hadith to every home across the world, and to nurture a generation that combines knowledge, practice, and character — working for the betterment of humanity and illuminating the world with the guidance of Allah's Deen.`,
      goal1: 'Global Outreach',
      goal1Desc: `Delivering the light of the Qur'an and Hadith to every household around the world.`,
      goal2: 'Guiding Towards the Right Path',
      goal2Desc: 'Helping the misguided return to the pure and beautiful path of Islam.',
      goal3: 'Generation Building',
      goal3Desc: 'Raising an ideal generation grounded in knowledge, righteous actions, and noble character.',
      goal4: 'Spreading Authentic Knowledge',
      goal4Desc: `Promoting the correct understanding of the Qur'an and Sunnah worldwide.`,
      goal5: 'Quality Education',
      goal5Desc: 'Ensuring world-class online Islamic education for learners everywhere.',
      goal6: 'Easy Accessibility',
      goal6Desc: 'Making Islamic education accessible to all through modern technology.',
      commitmentsTitle: 'Our Commitments',
      commitment1: 'To provide personalized attention to every student.',
      commitment2: 'To use the highest quality teaching materials and methods.',
      commitment3: 'To support students in developing moral and ethical excellence.',
      commitment4: `To deliver a correct and clear understanding of the Qur'an and Sunnah.`,
      commitment5: 'To maintain a simple, comfortable, and effective learning environment.',
    },
    features: {
      title: 'Our Features',
      subtitle: 'That Makes Us Different',
      feature1: 'One-on-One Classes',
      feature1Desc: 'One teacher for one student — complete personal attention.',
      feature2: 'Group Classes',
      feature2Desc: 'Effective learning in small groups of 3–5 students.',
      feature3: 'Flexible Schedule',
      feature3Desc: 'Attend classes at your convenience.',
      feature4: 'Experienced Male & Female Teachers',
      feature4Desc: 'Male teachers for brothers and female teachers for sisters.',
      feature5: 'Free Trial Classes',
      feature5Desc: 'Enjoy multiple free trial classes before admission.',
      feature6: 'Fast Learning',
      feature6Desc: `Learn to read the Qur'an beautifully in just 4 months.`,
      feature7: 'Continuous Monitoring',
      feature7Desc: `Students' progress is regularly observed and evaluated.`,
      feature8: 'Monthly Assessment',
      feature8Desc: 'Regular exams and progress reports are provided.',
      feature9: 'Time Management',
      feature9Desc: 'Each course runs 5 days a week; class days can be adjusted upon discussion.',
      classMethodTitle: 'Class Method',
      classMethodText: 'All classes are conducted fully online, allowing students to learn easily from home.',
      platformsTitle: 'Platforms Used',
    },
    policies: {
      title: 'Policies',
      subtitle: 'Institutional Rules and Regulations',
      classPolicyTitle: 'Class Policy',
      classPolicy1: 'Students must attend every class on time. Please be ready at least 5 minutes before class begins.',
      classPolicy2: 'Ensure a stable internet connection before joining the class.',
      classPolicy3: `Stay focused and attentive, and follow the teacher's instructions carefully.`,
      classPolicy4: 'Each one-to-one class lasts 40–45 minutes, and each group class lasts 50–60 minutes. Class duration may be adjusted upon mutual discussion.',
      attendanceTitle: 'Attendance and Leave',
      attendance1: 'If you need to miss a class, please inform your teacher at least 24 hours in advance.',
      attendance2: 'In case of emergencies, a make-up class may be arranged.',
      attendance3: 'If a student is absent for 3 consecutive classes without notice, a warning will be issued.',
      conductTitle: 'Code of Conduct',
      conduct1: 'Show respect to your teachers and classmates at all times.',
      conduct2: 'Maintain Islamic manners and etiquette during classes.',
      conduct3: 'Any form of unethical or inappropriate behavior will not be tolerated.',
      conduct4: 'Avoid financial transactions with teachers or classmates without prior acquaintance or permission.',
      paymentTitle: 'Payment and Refund Policy',
      payment1: 'Monthly fees must be paid between the 1st and 5th of each month.',
      payment2: 'The admission fee is non-refundable under any circumstances.',
      payment3: 'Once a course has started, no refunds will be issued for cancellations.',
      payment4: 'If the course is canceled within the first 7 days, a 50% refund will be provided.',
    },
    footer: {
      about: 'Al-Maarif',
      institute: 'International Institute',
      description: 'Spreading the light of the Quran and Hadith to every home around the world.',
      quickLinks: 'Quick Links',
      aboutUs: 'About Us',
      courses: 'Courses',
      admissionProcess: 'Admission Process',
      teachers: 'Teachers Panel',
      contact: 'Contact',
      socialMedia: 'Social Media',
      rights: 'Al-Maarif International Institute. All rights reserved.',
      establishedDate: 'Date of Establishment: 12 October 2025 CE / 20 Rabi al-Thani 1447 AH / 27 Ashwin 1432 BS',
    },
    contact: {
      title: 'Need Advice?',
      subtitle: 'We are always ready to assist you. Feel free to contact us with any questions or suggestions.',
      formTitle: 'Contact Form',
      name: 'Name',
      namePlaceholder: 'Enter your full name',
      email: 'Email',
      emailPlaceholder: 'example@email.com',
      phone: 'Mobile Number',
      phonePlaceholder: '+880 __________',
      subject: 'Subject',
      subjectPlaceholder: 'Enter the subject',
      message: 'Message',
      messagePlaceholder: 'Type your message here',
      sendMessage: 'Send Message',
      contactInfo: 'Contact Information',
      officeHours: 'Office Hours',
      officeHoursText: 'Saturday – Thursday: 9:00 AM – 8:00 PM',
      friday: 'Friday: Closed',
      emergencySupport: 'Emergency Support',
      emergencyText: 'For urgent matters, contact our hotline directly:',
      hotline: 'Hotline',
      successTitle: 'Success!',
      successMessage: 'Your message has been sent successfully.',
      errorTitle: 'Error!',
      errorMessage: 'Failed to send message. Please try again.',
      validationError: 'Please fill in all required fields.',
    },
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'bn') ? saved : 'bn';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
